import Image from "next/image";
import styles from "../styles/index.module.css";
import homeImage from "../public/home.png";
import { BiSolidUserCircle } from "react-icons/bi";
import { useEffect, useRef, useState } from "react";
import { RiLockPasswordFill } from "react-icons/ri";
import backgroundImg from "../public/background.png";
import Head from "next/head";
import { NextRouter, useRouter } from "next/router";
import { notification } from "antd";
import { serverUrl } from "@/data/server";

export default function EditPage() {
  const usernameRef = useRef<HTMLInputElement>(null);
  const passwordRef = useRef<HTMLInputElement>(null);
  const confirmPassRef = useRef<HTMLInputElement>(null);
  const [isFirst, setIsFirst] = useState(true);
  const router: NextRouter = useRouter();
  //   console.log(router.query);
  const [api, contextHolder] = notification.useNotification();
  const [loading, setLoading] = useState(false);

  const [token, setToken] = useState("");

  useEffect(() => {
    if (usernameRef.current) {
      usernameRef.current.value = router.query.email as string;
    }
    if (typeof window !== "undefined" && window.localStorage) {
      const dtoken = localStorage.getItem("token");
      // console.log(dtoken);
      if (dtoken != null) {
        setToken(dtoken);
      }
    }
  }, [router]);

  const formSubmitHandler = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setLoading(true);
    const email = usernameRef.current?.value;
    const password = passwordRef.current?.value;
    const confirmPassword = confirmPassRef.current?.value;

    if (email == null || password == null || confirmPassword == null) {
      return;
    }

    try {
      const res = await fetch(
        `${serverUrl}/user/update/${router.query.userId}`,
        {
          method: "POST",
          body: JSON.stringify({
            email: email,
            password: password,
            confirmPassword: confirmPassword,
          }),
          headers: {
            "Content-Type": "application/json",
            Authorization: `bearer ${token}`,
          },
        }
      );
      const data = await res.json();
      if (data.error) {
        api["error"]({
          message: data.error,
          duration: 10,
        });
      }

      if (data.result) {
        api["success"]({
          message: "User data updated Successfully",
          duration: 5,
        });
        router.replace("/dashboard");
      }
    } catch (error) {
      api["info"]({
        message: "Something went wrong, Please try again later.",
        duration: 10,
      });
    }
    if (usernameRef.current) {
      usernameRef.current.value = "";
    }
    if (passwordRef.current) {
      passwordRef.current.value = "";
    }
    if (confirmPassRef.current) {
      confirmPassRef.current.value = "";
    }
    setLoading(false);
  };

  return (
    <>
      <Head>
        <title>Cryptography and network security</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {contextHolder}
      <div className={styles.container}>
        <div className={styles.imgContainer}>
          <Image src={homeImage} alt="home page image" />
        </div>
        <div className={styles.formContainer}>
          <div className={styles.background}>
            <Image src={backgroundImg} alt="background image" />
          </div>
          <h1>Update User Data</h1>
          <form className={styles.form} onSubmit={formSubmitHandler}>
            <div className={styles.formDiv}>
              <label className={styles.title}>
                <BiSolidUserCircle /> <p>Email</p>
              </label>
              <input type="email" ref={usernameRef} required />
            </div>
            <div className={styles.formDiv}>
              <label className={styles.title}>
                <RiLockPasswordFill /> <p>Password</p>
              </label>
              <input type="password" ref={passwordRef} required />
            </div>
            <div className={styles.formDiv}>
              <label className={styles.title}>
                <RiLockPasswordFill /> <p>Confirm Password</p>
              </label>
              <input type="password" ref={confirmPassRef} required />
            </div>
            {loading && <span className={styles.loader}></span>}
            {!loading && <button type="submit">Update User</button>}

            {/* <div className={styles.shift}>
              <p
                onClick={() => {
                  router.replace("/");
                }}
              >
                Already have an account ?
              </p>
            </div> */}
          </form>
        </div>
      </div>
    </>
  );
}
