import Image from "next/image";
import styles from "../styles/index.module.css";
import homeImage from "../public/home.png";
import { BiSolidUserCircle } from "react-icons/bi";
import { useRef } from "react";
import { RiLockPasswordFill } from "react-icons/ri";
import backgroundImg from "../public/background.png";
import Head from "next/head";
import { NextRouter, useRouter } from "next/router";

export default function SingupPage() {
  const usernameRef = useRef<HTMLInputElement>(null);
  const passwordRef = useRef<HTMLInputElement>(null);
  const confirmPassRef = useRef<HTMLInputElement>(null);
  const router: NextRouter = useRouter();

  return (
    <>
      <Head>
        <title>Cryptography and network security</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <div className={styles.imgContainer}>
          <Image src={homeImage} alt="home page image" />
        </div>
        <div className={styles.formContainer}>
          <div className={styles.background}>
            <Image src={backgroundImg} alt="background image" />
          </div>
          <h1>SIGN UP</h1>
          <form className={styles.form}>
            <div className={styles.formDiv}>
              <label className={styles.title}>
                <BiSolidUserCircle /> <p>Email</p>
              </label>
              <input type="email" ref={usernameRef} required />
            </div>
            <div className={styles.formDiv}>
              <label className={styles.title}>
                <RiLockPasswordFill /> <p>Password</p>
              </label>
              <input type="password" ref={passwordRef} required />
            </div>
            <div className={styles.formDiv}>
              <label className={styles.title}>
                <RiLockPasswordFill /> <p>Confirm Password</p>
              </label>
              <input type="password" ref={confirmPassRef} required />
            </div>
            <button type="submit">Sign Up</button>
            <div className={styles.shift}>
              <p
                onClick={() => {
                  router.replace("/");
                }}
              >
                Already have an account ?
              </p>
            </div>
          </form>
        </div>
      </div>
    </>
  );
}
